# strategies/mean_reversion.py
import pandas as pd
import pandas_ta as ta
import numpy as np

class MeanReversionStrategy:
    """
    Looks for prices that have stretched too far from their average 
    and bets on them snapping back to the middle using Bollinger Bands and RSI.
    """
    
    def __init__(self, bb_length: int = 20, bb_std: float = 2.0, rsi_length: int = 14):
        self.bb_length = bb_length
        self.bb_std = bb_std
        self.rsi_length = rsi_length
        
    def analyze(self, df: pd.DataFrame) -> dict:
        # 1. Check for sufficient data
        if df is None or len(df) < max(self.bb_length, self.rsi_length):
            return {"action": "WAIT", "confidence": 0.0, "reason": "Not enough data points."}

        # 2. Calculate Indicators
        # Bollinger Bands (pandas_ta returns a DataFrame with Lower, Mid, and Upper bands)
        bb = ta.bbands(df['close'], length=self.bb_length, std=self.bb_std)
        if bb is not None:
            df = pd.concat([df, bb], axis=1)
            
        # RSI
        df['rsi'] = ta.rsi(df['close'], length=self.rsi_length)
        
        # Original Ratio Calculation
        df['sma'] = ta.sma(df['close'], length=21)
        df['ratios'] = df['close'] / df['sma']
        
        # Clean NaNs caused by indicator windows
        df.dropna(inplace=True)
        if df.empty:
            return {"action": "WAIT", "confidence": 0.0, "reason": "Data dropped to empty."}

        # --- FIX: Calculate Percentile Thresholds Correctly ---
        percentiles = [15, 85]
        percentile_values = np.percentile(df['ratios'], percentiles)
        buy_threshold = percentile_values[0]   # Correctly mapped to the calculated value
        sell_threshold = percentile_values[1]  # Correctly mapped to the calculated value
        
        df['ratio_position'] = np.where(df['ratios'] > sell_threshold, -1, 
                                        np.where(df['ratios'] < buy_threshold, 1, 0))

        # --- SIGNAL GENERATION LOGIC ---
        last_row = df.iloc[-1]
        close = last_row['close']
        rsi = last_row['rsi']
        
        # Dynamic column names generated by pandas_ta
        bb_lower = f"BBL_{self.bb_length}_{self.bb_std}"
        bb_upper = f"BBU_{self.bb_length}_{self.bb_std}"

        action = "WAIT"
        confidence = 0.0
        reason = "Price is within normal bounds."

        if bb_lower in df.columns and bb_upper in df.columns:
            lower_band = last_row[bb_lower]
            upper_band = last_row[bb_upper]

            # CONFLUENCE 1: Bollinger Band Breakout + RSI Oversold/Overbought
            if close < lower_band and rsi < 30:
                action = "BUY"
                confidence = 0.85
                reason = f"Price ({close:.4f}) dropped below Lower BB ({lower_band:.4f}) with Oversold RSI ({rsi:.1f})."
                
            elif close > upper_band and rsi > 70:
                action = "SELL"
                confidence = 0.85
                reason = f"Price ({close:.4f}) broke above Upper BB ({upper_band:.4f}) with Overbought RSI ({rsi:.1f})."

            # CONFLUENCE 2: Backup logic using your fixed ratio
            elif last_row['ratio_position'] == 1 and rsi < 40:
                action = "BUY"
                confidence = 0.60
                reason = f"Price is stretched below SMA (Ratio oversold) with RSI ({rsi:.1f})."
                
            elif last_row['ratio_position'] == -1 and rsi > 60:
                action = "SELL"
                confidence = 0.60
                reason = f"Price is stretched above SMA (Ratio overbought) with RSI ({rsi:.1f})."

        return {"action": action, "confidence": confidence, "reason": reason}