# strategies/scalping.py
import pandas as pd
import pandas_ta as ta

class ScalpingStrategy:
    """
    High-frequency micro-trend catcher. Uses fast EMAs to determine direction
    and Stochastic crossovers for pinpoint entries.
    """
    
    def __init__(self, ema_fast: int = 5, ema_slow: int = 13, stoch_k: int = 5, stoch_d: int = 3):
        self.ema_fast = ema_fast
        self.ema_slow = ema_slow
        self.stoch_k = stoch_k
        self.stoch_d = stoch_d

    def analyze(self, df: pd.DataFrame) -> dict:
        """
        Takes a dataframe of M1 or M5 price history and returns a rapid trading signal.
        """
        if df is None or len(df) < self.ema_slow + 5:
            return {"action": "WAIT", "confidence": 0.0, "reason": "Not enough data"}

        # 1. Calculate Fast and Slow EMAs
        df['EMA_Fast'] = ta.ema(df['close'], length=self.ema_fast)
        df['EMA_Slow'] = ta.ema(df['close'], length=self.ema_slow)

        # 2. Calculate Stochastic Oscillator
        # Returns %K (Fast line) and %D (Slow signal line)
        stoch_df = ta.stoch(df['high'], df['low'], df['close'], k=self.stoch_k, d=self.stoch_d, smooth_k=3)
        if stoch_df is None:
             return {"action": "WAIT", "confidence": 0.0, "reason": "Indicator calculation failed"}
             
        df = pd.concat([df, stoch_df], axis=1)

        # 3. Get the latest closed candle and the one before it (to detect crossovers)
        latest = df.iloc[-2]
        previous = df.iloc[-3]

        # Dynamically find the Stochastic column names generated by pandas-ta
        k_col = f"STOCHk_{self.stoch_k}_{self.stoch_d}_3"
        d_col = f"STOCHd_{self.stoch_k}_{self.stoch_d}_3"
        
        ema_fast = latest['EMA_Fast']
        ema_slow = latest['EMA_Slow']
        
        # Current Stochastic
        k_live = latest[k_col]
        d_live = latest[d_col]
        
        # Previous Stochastic
        k_prev = previous[k_col]
        d_prev = previous[d_col]

        # 4. The Logic Rules
        
        # BUY SIGNAL: 
        # Micro-trend is UP (Fast > Slow) AND Stochastic %K just crossed ABOVE %D AND we aren't overbought (< 80)
        if ema_fast > ema_slow and (k_prev <= d_prev and k_live > d_live) and k_live < 80.0:
            
            # Confidence is highest if we catch the crossover deep in oversold territory (< 20)
            confidence = min(0.99, 0.80 + ((20.0 - k_live) / 100.0) if k_live < 20 else 0.75)
            return {
                "action": "BUY", 
                "confidence": round(confidence, 2), 
                "reason": f"Scalp Long (Micro-trend UP, Stoch crossed up at {k_live:.1f})"
            }

        # SELL SIGNAL: 
        # Micro-trend is DOWN (Fast < Slow) AND Stochastic %K just crossed BELOW %D AND we aren't oversold (> 20)
        elif ema_fast < ema_slow and (k_prev >= d_prev and k_live < d_live) and k_live > 20.0:
            
            # Confidence is highest if we catch the crossover deep in overbought territory (> 80)
            confidence = min(0.99, 0.80 + ((k_live - 80.0) / 100.0) if k_live > 80 else 0.75)
            return {
                "action": "SELL", 
                "confidence": round(confidence, 2), 
                "reason": f"Scalp Short (Micro-trend DOWN, Stoch crossed down at {k_live:.1f})"
            }

        # DEFAULT: Wait for a clear setup
        return {"action": "WAIT", "confidence": 0.0, "reason": "No micro-momentum crossover."}